"""add columns to table

Revision ID: 458a97d59e79
Revises: 67f5d67aea55
Create Date: 2025-06-18 17:42:07.126836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458a97d59e79'
down_revision = '67f5d67aea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
